version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.12"
  commands:
    - pip install myst_parser


sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
