version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
  commands:
    - pip install myst_parser
  # - build --site-dir $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: doc/conf.py
  builder: html

formats:
  - pdf

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: .
      # extra_requirements:
      #   - docs
