version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install myst_parser

# Optionally build your docs in additional formats such as PDF and ePub

formats:
   - pdf
   - epub


sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
