
# Project information
site_name: S7-1200PLC技术手册 - EasyPlus
site_url: 
site_author: Frank Lin
site_description: >- 
  西门子 S7-1200 PLC 技术参考,Ver4.3

# Repository
repo_name: lybhb8/S7-1200-EasyPlus
repo_url: https://github.com/lybhb8/S7-1200EasyPlus

# Copyright
copyright: Copyright &copy; 2016 - 2024 FrankLin & lybhb8

# Configuration
theme: 
  name: readthedocs # mkdocs # material # 
  custom_dir: material/overrides
  features:

    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # deep purple
      accent:  indigo # deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  icon:
    logo: logo

# Plugins
plugins:
  #- blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\: )"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
hooks:
  - material/overrides/hooks/shortcodes.py
  - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lybhb8
    - icon: fontawesome/brands/blogger
      link: https://blowmoldingshare.cn/      
    - icon: fontawesome/solid/s
      link: https://www.ad.siemens.com.cn/download/filter?productTypeId=1224
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mkdocs-material/

    # - icon: fontawesome/brands/x-twitter
    # link: https://x.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences

  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md

# Page tree


nav:
  - 基础综述: 
    - index.md
    - S7-1200简介: introduction\index.md
    - 网络资源: source\index.md
    - S7-1200硬件: 
      - hardware\index.md
      - 参数总汇: specifications\parameters.md
      - 性能参数V4.0: specifications\feature.md
    - S7-1200版本: 
      - 04-version\index.md
      - CPU 固件常见问题: 04-version\02-Version\question.md
      - PLC V4.6 简介: 04-version\02-Version\S7-1200_V4.6.md
      - 固件升级: 
        - 04-version\03-firmware_update\index.md
        - CPU固件: 04-version\03-firmware_update\firmware.md
        - 模块固件: 04-version\03-firmware_update\firmware1.md
  
  - 组态编程:

    #- STEP7 V18 安装: 07-Program\install.md
    - TIA Portal组态软件操作:
      - 07-Program\01-operation\index.md
      - STEP7 V18 安装: 07-Program\install.md 
      - 新建项目: 07-Program\01-operation\01-New_Project.md
      - CPU参数配置: 07-Program\01-operation\02-CPU_Properties.md
      - 常见问题FAQ: 07-Program\01-operation\03-ConfigFAQ.md
      - 项目下载: 07-Program\01-operation\04-Download.md
      - 运行下载: 07-Program\01-operation\05-download_run.md
      - 硬件检测: 07-Program\01-operation\06-detect_hardware.md
      - 上载程序: 07-Program\01-operation\07-upload_program.md
      - 上载站点: 07-Program\01-operation\08-upload_station.md
      - 上传时版本的兼容性: 07-Program\01-operation\09-upload_compatibility.md
      - 项目升级: 07-Program\01-operation\10-update.md
      - 程序升级: 07-Program\01-operation\11-Program_Update.md

    - 编程基础:
      - 07-Program\\02-basic\index.md
      - 数据类型: 
        - 07-Program\02-basic\01-Data_Type\index.md
        - 基本数据: 07-Program\02-basic\01-Data_Type\01-basic.md
        - 结构数据Struct: 07-Program\02-basic\01-Data_Type\02-Struct.md
        - UDT: 07-Program\02-basic\01-Data_Type\03-UDT.md
        - 数组: 07-Program\02-basic\01-Data_Type\04-Array.md
        - 系统数据SDT: 07-Program\02-basic\01-Data_Type\05-SDT.md
        - 硬件数据: 07-Program\02-basic\01-Data_Type\06-hardware.md
        - Variant: 07-Program\02-basic\01-Data_Type\07-Variant.md
        - DB_ANY: 07-Program\02-basic\01-Data_Type\08-DB_ANY.md
        - 字符String: 07-Program\02-basic\01-Data_Type\09-String.md
        - 宽字符WString: 07-Program\02-basic\01-Data_Type\10-WString.md
        - 时间数据DTL: 07-Program\02-basic\01-Data_Type\11-DTL.md

      - 组织块 OB: 
        - 组织块 OB简介: 07-Program\02-basic\02-OB\01-intro.md
        - 程序循环 OB1: 07-Program\02-basic\02-OB\02-OB1.md
        - 延时中断 OB20: 07-Program\02-basic\02-OB\03-OB20.md
        - 循环中断 OB30: 07-Program\02-basic\02-OB\04-OB30.md
        - 硬件中断 OB40: 07-Program\02-basic\02-OB\05-OB40.md
        - 时间错误 OB80: 07-Program\02-basic\02-OB\06-OB80.md
        - 诊断错误 OB82: 07-Program\02-basic\02-OB\07-OB82.md
        - 启动 OB100: 07-Program\02-basic\02-OB\08-OB100.md
        - 时间中断 OB10: 07-Program\02-basic\02-OB\09-OB10.md
        - 插拔中断 OB83: 07-Program\02-basic\02-OB\10-OB83.md
        - 机架或站故障 OB86: 07-Program\02-basic\02-OB\11-OB86.md

      - FC功能、FB功能块: 
        - 07-Program\02-basic\03-Block\index.md
        - FC功能: 07-Program\02-basic\03-Block\01-FC.md
        - DB数据块: 07-Program\02-basic\03-Block\02-DB.md
        - DB快照功能: 07-Program\02-basic\03-Block\03-DB_Snapshots.md
        - FB功能块: 07-Program\02-basic\03-Block\04-FB.md

    - 编程指令:
      - 07-Program\03-instruction\index.md
      - 基础指令: 
        #- 07-Program\03-instruction\\01-Basic\index.md 
        - 位逻辑指令: 07-Program\03-instruction\01-Basic\08-bit.md
        - 置位和复位指令: 07-Program\03-instruction\01-Basic\09-set.md
        - 上升沿和下降沿: 07-Program\03-instruction\01-Basic\07-Edge.md
        - 定时器: 07-Program\03-instruction\01-Basic\01-TIMER.md
        - 计数器: 07-Program\03-instruction\01-Basic\02-COUNTER.md
        - 比较指令: 
          - 07-Program\03-instruction\01-Basic\03-compare\index.md
          - 值比较: 07-Program\03-instruction\01-Basic\03-compare\eq_value.md
          - 范围值比较: 07-Program\03-instruction\01-Basic\03-compare\eq_range.md
          - OK有效性比较: 07-Program\03-instruction\01-Basic\03-compare\eq_ok.md
          - 变量比较: 07-Program\03-instruction\01-Basic\03-Compare_Variant.md
        - 移动操作: 
          - 07-Program\03-instruction\01-Basic\04-Move\index.md
          - MOVE系列: 07-Program\03-instruction\01-Basic\04-Move\01-MOVE.md
          - 序列化: 07-Program\03-instruction\01-Basic\04-Move\02-DeserializeSerialize.md
          - FILL_BLK: 07-Program\03-instruction\01-Basic\04-Move\03-FILL_BLK.md
          - 位序列的组合与分解: 07-Program\03-instruction\01-Basic\04-Move\04-SCATTERGATHER.md
          - 移动操作-Variant: 07-Program\03-instruction\01-Basic\04-Move\05-MOVE_Variant.md
        - 程序控制:
          - GetError: 07-Program\03-instruction\01-Basic\05-Program_Control\01-GetError_GetErrorID.md
          - RUNTIME: 07-Program\03-instruction\01-Basic\05-Program_Control\02-RUNTIME.md
        - 移位和循环: 07-Program\03-instruction\01-Basic\06-Shift_and_Rotate.md
        - 数学函数:
          - 07-Program\03-instruction\01-Basic\10-Math_functions\index.md
          - 数学计算: 07-Program\03-instruction\01-Basic\10-Math_functions\calculate.md
          - 加减乘除: 07-Program\03-instruction\01-Basic\10-Math_functions\add.md
          - 取模: 07-Program\03-instruction\01-Basic\10-Math_functions\mod.md
          - 取反: 07-Program\03-instruction\01-Basic\10-Math_functions\neg.md
          - 递增和递减: 07-Program\03-instruction\01-Basic\10-Math_functions\inc_dec.md
          - 绝对值: 07-Program\03-instruction\01-Basic\10-Math_functions\abs.md
          - 最小值和最大值: 07-Program\03-instruction\01-Basic\10-Math_functions\max_min.md
          - 极限值: 07-Program\03-instruction\01-Basic\10-Math_functions\limit.md
          - 指数、对数及三角函数: 07-Program\03-instruction\01-Basic\10-Math_functions\exponent.md
      - 扩展指令:
        - 日期和时间: 07-Program\03-instruction\02-Extend\01-Time.md
        - 字符串: 07-Program\03-instruction\02-Extend\02-String.md
        - 读取序列号: 07-Program\03-instruction\02-Extend\03-Others\01-Get_IM_Data.md
        - 判断程序改动: 07-Program\03-instruction\02-Extend\03-Others\02-GetChecksum.md
        - 应用例程: 07-Program\03-instruction\02-Extend\04-ApplicationExample.md
